sources:
  - name: raw       # Este será el "alias" del dataset gz_raw_data
    schema: gz_raw_data
    tables:
      - name: raw_gz_sales
        alias: sales
      - name: raw_gz_product
        alias: product
      - name: raw_gz_ship
        alias: ship